export const types = {
	UPDATE_CODE_STRING: "UPDATE_CODE_STRING",
	UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
	TOGGLE_LANGUAGE_DROPDOWN: "TOGGLE_LANGUAGE_DROPDOWN",
	UPDATE_THEME: "UPDATE_THEME",
	TOGGLE_THEME_DROPDOWN: "TOGGLE_THEME_DROPDOWN",
	TOGGLE_LINE_NUMBERS_VISIBILITY: "TOGGLE_LINE_NUMBERS_VISIBILITY",
	UPDATE_SCREENSHOT_BG: "UPDATE_SCREENSHOT_BG",
	UPDATE_SCREENSHOT_DATA_URL: "UPDATE_SCREENSHOT_DATA_URL",
	TOGGLE_COLOR_PICKER: "TOGGLE_COLOR_PICKER",
};

export default types;
