export const types = {
	UPDATE_CODE_STRING: "UPDATE_CODE_STRING",
	UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
	UPDATE_THEME: "UPDATE_THEME",
	TOGGLE_LINE_NUMBERS_VISIBILITY: "TOGGLE_LINE_NUMBERS_VISIBILITY",
	UPDATE_SCREENSHOT_BG: "UPDATE_SCREENSHOT_BG",
	UPDATE_SCREENSHOT_DATA_URL: "UPDATE_SCREENSHOT_DATA_URL",
};

export default types;
